### ISSUE TITLE
rename working-doc to something with meaning

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#10]
...like "luminosity-function", since that is what the document is about

**Comment by aimalz** [comment]
That document started out as an overview of the broader project that will probably be my thesis, before I split it up into several other documents, one of which is this "minimal" project.  I'm turning the content into a general readme as @drphilmarshall suggested, but I took it down in the meantime because it's confusing to have it front and center like that.

**Comment by drphilmarshall** [comment]
Not sure what you mean by "took it down" - this is your working directory,
right? Throwing up a minimally explanatory README should fix things.

**Comment by aimalz** [comment]
I'm closing this issue because I reorganized the repository a few weeks ago and wrote a little readme.
